apiVersion: v1
kind: Service
metadata:
  name: devops-nodejs-service
spec:
  selector:
    app: devops-nodejs-app
  ports:
  - protocol: TCP
    port: 80  # Expose the service on port 80
    targetPort: 3000  # Internally forward traffic to container port 3000
  type: LoadBalancer  # Exposes the app to the internet